import Item from "../classes/Item";
import { Tiers } from "../classes/Tiers";
import { Currencies } from "../classes/Currencies";

const items = [
    new Item("grass", "Stone", Tiers.Common, 
        "A verdant, soft plant, covering the Chasm floors in lush patches, used in crafting for its flexibility and as a key ingredient in various natural remedies and lightweight armors.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png",
        { currency: Currencies.CP, amount: 1 }),
    new Item("stone", "Stone", Tiers.Common, 
        "A rugged gray mineral, ubiquitous in the depths, used in construction for its durability and as a basic crafting material for various essential tools and structures.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 1 }),
    new Item("coal", "Coal", Tiers.Common, 
        "This dense, black mineral is scattered throughout the depths. Known for its high combustibility, coal is essential for fueling forges and creating powerful explosives. It also serves as a crucial component in crafting various industrial tools and equipment.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 4 }),
    new Item("copper", "Copper", Tiers.Common, 
        "With a warm, reddish hue, copper veins weave through the earth like hidden treasure. Known for its exceptional conductivity and easy workability, copper is a favorite among crafters for making intricate mechanisms and beautiful ornaments.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 10 }),
    new Item("iron", "Iron", Tiers.Common, 
        "As robust gray metal, it forms the backbone of countless tools and structures. Its strength and versatility make it indispensable for forging mighty weapons and building resilient frameworks that stand the test of time.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 14 }),
    new Item("silver", "Silver", Tiers.Common, 
        "This luminous, white metal shimmers with a timeless elegance. Coveted for its unmatched conductivity and lustrous beauty, silver finds its way into exquisite jewelry, high-value currency, and finely-tuned electronic components.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 28 }),
    new Item("amber", "Amber", Tiers.Common, 
        "This golden, translucent gem, formed from ancient tree resin, glows with a warm, captivating light. Treasured for its organic beauty and unique properties, amber is used in crafting enchanting jewelry, mystical amulets, and potent elixirs.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 40 }),
    new Item("obsidian", "Obsidian", Tiers.Uncommon, 
        "A glassy, black volcanic rock, obsidian is prized for its sharp edges and mystical properties. Often used in crafting precision tools, protective amulets, and dark, powerful artifacts.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 70 }),
    new Item("amethyst", "Amethyst", Tiers.Uncommon, 
        "A vibrant, purple gemstone, amethyst radiates a serene, calming energy. Sought after for its beauty and supposed healing properties, it is used in creating elegant jewelry and mystical charms.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 90 }),
    new Item("titanium", "Titanium", Tiers.Uncommon, 
        "This strong, lightweight metal is rare and highly valued. Known for its resilience and resistance to corrosion, titanium is used in crafting advanced tools, durable armor, and high-performance equipment.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 110 }),
    new Item("onyx", "Onyx", Tiers.Uncommon, 
        "A sleek, black gemstone with a polished surface, onyx is often associated with strength and protection. Commonly used in sophisticated jewelry, ornate decorations, and powerful talismans.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 180 }),
    new Item("quartz", "Quartz", Tiers.Uncommon, 
        "Gleaming with a crystalline brilliance, quartz is a versatile gem that captures light and imagination. Its clear, radiant shards are often used in precision instruments, enchanting decorations, and intricate timepieces.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 185 }),
    new Item("palladium", "Palladium", Tiers.Uncommon, 
        "This rare, silvery-white metal is renowned for its exceptional purity and resistance to corrosion. Valued for its use in advanced technology and delicate craftsmanship, palladium is a key material in high-end electronics.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 280 }),
    new Item("luminarium", "Luminarium", Tiers.Rare, 
        "A radiant, luminescent crystal that emits a soft, nostalgic glow. Luminarium is sought after for its ability to store and release energy, making it essential for crafting powerful light sources and enchanted devices.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 1650 }),
    new Item("voidstone", "Voidstone", Tiers.Rare, 
        "Dark and seemingly absorbing all light around it, Voidstone feels heavier than it looks. It's key to creating devices that bend the rules of space, allowing for teleportation or gravity manipulation.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 1650 }),
    new Item("aetherflux", "Aetherflux", Tiers.Rare, 
        "This ethereal substance shimmers with an otherworldly light, almost weightless to the touch. It conducts magical energies like no other, making it invaluable for crafting artifacts that require intense magical power.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 3400 }),
    new Item("cadmium", "Cadmium", Tiers.Rare, 
        "This striking bluish-white metal is renowned for its unusual properties and rarity. Often found in intricate geological formations, Cadmium is used in specialized crafting for its unique ability to shield against harmful spectra and stabilize volatile materials.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 3500 }),
    new Item("platinum", "Platinum", Tiers.Rare, 
        "Platinum exudes both elegance and strength. It's not just a symbol of wealth; its unique properties make it indispensable in crafting artifacts that require unparalleled resilience and stability. Often used in binding powerful enchantments, Platinum's rarity only adds to its mystique and value.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 4800 }),
    new Item("frostglass", "Frostglass", Tiers.Rare, 
        "Dark and seemingly absorbing all light around it, Voidstone feels heavier than it looks. It's key to creating devices that bend the rules of space, allowing for teleportation or gravity manipulation.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 6000 }),
    new Item("gold", "Gold", Tiers.Epic, 
        "A lustrous yellow metal, found in rare veins throughout the Chasm, prized for its malleability and conductivity, often used in high-value trade, intricate jewelry, and advanced magical enhancements.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 7000 }),
    new Item("eclipseOrb", "Eclipse Orb", Tiers.Epic, 
        "A mysterious, perfectly black sphere, the Eclipse Orb holds the essence of a solar eclipse. It's used in powerful rituals and artifacts to manipulate light and darkness, creating impenetrable shadows or dazzling illusions.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 7800 }),
    new Item("celestialTapestry", "Celestial Tapestry", Tiers.Epic, 
        "Woven from threads of starlight and moonbeams, this magical fabric shimmers with the constellations. It was once used to create enchanted garments that grant the wearer protection and wisdom of the cosmos.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 8700 }),
    new Item("moltenCore", "Molten Core", Tiers.Epic, 
        "A globe of pure, plasmatic fire contained within a crystal shell, the Molten Core radiates intense heat. It's a powerful component in forging weapons and armor that channel the destructive force of volcanic eruptions.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 11600 }),
    new Item("dreamweaversLoom", "Dreamweaver's Loom", Tiers.Epic, 
        "An ancient and miniscule contraption that can weave the fabric of dreams into reality. Items created with this loom hold the power to influence thoughts and emotions.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 18000 }),
    new Item("chronal", "Chronal", Tiers.Epic, 
        "Shards of these crystals seem to distort time around them. When integrated into weaponry, they can slow down or speed up time, making them invaluable for both offensive and defensive applications.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CP, amount: 28000 }),
    new Item("apoptosis", "Apoptosis", Tiers.Legendary, 
        "This mysterious, crystalline enigma pulses with a dark, rhythmic energy. Named after the process of programmed cell death, Apoptosis is a long-forgotten artifact once used to dismantle and disintegrate corrupt or malignant entities. When invoked, it cleanses areas of dark influences, restoring balance and order to the surroundings.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png", 
        { currency: Currencies.CX, amount: 1 }),
    new Item("singularity", "Singularity", Tiers.Legendary, 
        "It appears as a swirling, iridescent void encased in a translucent shell. The surface shimmers with colors that seem to shift and change, drawing the eye into its depths. Within the core, faint, swirling galaxies and starbursts hint at its unfathomable power. Unearthed from the darkest depths, the Singularity's presence is a paradox of mesmerizing beauty and intense gravity, as if holding the very fabric of the cosmos within.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png",
        { currency: Currencies.CX, amount: 1 }),
    new Item("myceliumNexus", "Mycelium Nexus", Tiers.Legendary, 
        "A sprawling network of bioluminescent fungi that pulses with a soft, green light. The Mycelium Nexi connect all plant life, acting as a living, breathing web of communication. It is said to store the collective memories and knowledge of the ecosystem, offering insights to those who learn to commune with it.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png",
        { currency: Currencies.CX, amount: 2 }),
    new Item("twistedFlesh", "Twisted Flesh", Tiers.Legendary, 
        "An amorphous mass that pulses with life. An indefinite number of hallucinations reaves your mind as you gaze upon it. It whispers forbidden transformations, merging pain and ecstasy in a visceral dance of chaos.", 
        "https://i.postimg.cc/7Y81Rmm9/Common-Rocks.png",
        { currency: Currencies.CX, amount: 3 }),
]

const itemsMap = new Map(items.map(item => [item.id, item])) as Map<string, Item>;

export default itemsMap;